highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: http://morenjojo.github.io/
devurl: http://localhost:4000/
name: Vc.work
title: Moren jojo | Another yet unique freak is showing a freakshow
description: "Morenjojo's personal weblog, on coding or such stuff"

my:
    displayName: Moren jojo
    realName: Wang Yanchen
    realName_cn: 王衍晨
    jobTitle: "iOS Coder"
    contact:
        qq: 1678453
        email: 1678453@qq.com
        github: http://www.github.com/morenjojo
        qzone: http://1678453.qzone.qq.com
        weibo: http://weibo.com/u/1051713905
        tel: 15811275153
        address:
            country: China
            state: ShanDong
            city: ZiBo
            distribute: ZiChuan
            postcode: 255100
            cell: "PanYang"
    skills:
        frontend: ["iOS | Objective-C Swift"]
        backend: ["PHP", "MySQL", "Redis", "Regex", "Laravel", "OSC", "前面的都不会 囧"]
        tools: ["iOS | Xcode", "Text Mate", "MacDown", "Git | Github", "Mac OS", "Jekyll | Liquid"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare